In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision

TỰ LUẬN

CÂU 1

In [ ]:
class Softmax(nn.Module):
    def __init__(self):
        super(Softmax, self).__init__()

    def forward(self, x):
        exp_x = torch.exp(x)
        sum_exp_x = torch.sum(exp_x)
        softmax = exp_x / sum_exp_x
        return softmax

class SoftmaxStable(nn.Module):
    def __init__(self):
        super(SoftmaxStable, self).__init__()

    def forward(self, x):
        shift_x = x - torch.max(x)
        exp_x = torch.exp(shift_x)
        sum_exp_x = torch.sum(exp_x)
        softmax = exp_x / sum_exp_x
        return softmax

Softmax Output: tensor([0.0900, 0.2447, 0.6652])
Stable Softmax Output: tensor([0.0900, 0.2447, 0.6652])


example

In [ ]:
data = torch.Tensor([1, 2, 3])

# standard Softmax
softmax = Softmax()
output = softmax(data)
print("Softmax Output:", output)

# stable version of Softmax
softmax_stable = SoftmaxStable()
output_stable = softmax_stable(data)
print("Stable Softmax Output:", output_stable)

Softmax Output: tensor([0.0900, 0.2447, 0.6652])
Stable Softmax Output: tensor([0.0900, 0.2447, 0.6652])


TRẮC NGHIỆM

In [ ]:
# cau 1
softmax_function = nn.Softmax(dim=0)
output = softmax_function(data)
assert round(output[0].item(),2)==0.09
output

tensor([0.0900, 0.2447, 0.6652])

In [ ]:
# cau 2
data = torch.Tensor([5, 2, 4])
my_softmax = Softmax()
output = my_softmax(data)
assert round(output[-1].item(),2)==0.26
output

tensor([0.7054, 0.0351, 0.2595])

In [ ]:
# cau 3
data = torch.Tensor([1, 2, 300000000])
my_softmax = Softmax()
output = my_softmax(data)
assert round(output[0].item(),2)==0.0
output

tensor([0., 0., nan])

In [ ]:
# cau 4
class SoftmaxStable(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_max = torch.max(x, dim=0, keepdims=True)
        x_exp = torch.exp(x - x_max.values)
        partition = x_exp.sum(0, keepdims=True)
        return x_exp / partition

data = torch.Tensor([1, 2, 3])
softmax_stable = SoftmaxStable()
output = softmax_stable(data)
assert round(output[-1].item(), 2) == 0.67
output

tensor([0.0900, 0.2447, 0.6652])

CÂU 2

In [ ]:
class Person:
    def __init__(self, name, yob):
        self.name = name
        self.yob = yob

    def describe(self):
        pass

class Student(Person):
    def __init__(self, name, yob, grade):
        super().__init__(name, yob)
        self.grade = grade

    def describe(self):
        print(f"Student - Name: {self.name} - YoB: {self.yob} - Grade: {self.grade}")

class Teacher(Person):
    def __init__(self, name, yob, subject):
        super().__init__(name, yob)
        self.subject = subject

    def describe(self):
        print(f"Teacher - Name: {self.name} - YoB: {self.yob} - Subject: {self.subject}")

class Doctor(Person):
    def __init__(self, name, yob, specialist):
        super().__init__(name, yob)
        self.specialist = specialist

    def describe(self):
        print(f"Doctor - Name: {self.name} - YoB: {self.yob} - Specialist: {self.specialist}")

class Ward:
    def __init__(self, name):
        self.name = name
        self.people = []

    def add_person(self, person):
        self.people.append(person)

    def describe(self):
        print(f"Ward Name: {self.name}")
        for person in self.people:
            person.describe()

    def count_doctor(self):
        return sum(isinstance(person, Doctor) for person in self.people)

    def sort_age(self):
        self.people.sort(key=lambda person: person.yob)

    def compute_average(self):
        teachers = [person.yob for person in self.people if isinstance(person, Teacher)]
        return sum(teachers) / len(teachers) if teachers else 0


example

In [ ]:
# 2(a)
student1 = Student(name="studentA", yob=2010, grade="7")
student1.describe ()
teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
teacher1.describe ()
doctor1 = Doctor(name="doctorA", yob=1945, specialist="Endocrinologists")
doctor1.describe()

Student - Name: studentA - YoB: 2010 - Grade: 7
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Doctor - Name: doctorA - YoB: 1945 - Specialist: Endocrinologists


In [ ]:
# 2(b)
teacher2 = Teacher(name="teacherB", yob=1995, subject="History")
doctor2 = Doctor(name="doctorB", yob=1975, specialist="Cardiologists")

ward1 = Ward(name="Ward1")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)

ward1.describe()

Ward Name: Ward1
Student - Name: studentA - YoB: 2010 - Grade: 7
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Teacher - Name: teacherB - YoB: 1995 - Subject: History
Doctor - Name: doctorA - YoB: 1945 - Specialist: Endocrinologists
Doctor - Name: doctorB - YoB: 1975 - Specialist: Cardiologists


In [ ]:
# 2(c)
print(f"\nNumber of doctors: {ward1.count_doctor()}")


Number of doctors: 2


In [ ]:
# 2(d)
print("\nAfter sorting Age of Ward1 people")
ward1.sort_age()
ward1.describe()


After sorting Age of Ward1 people
Ward Name: Ward1
Doctor - Name: doctorA - YoB: 1945 - Specialist: Endocrinologists
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Doctor - Name: doctorB - YoB: 1975 - Specialist: Cardiologists
Teacher - Name: teacherB - YoB: 1995 - Subject: History
Student - Name: studentA - YoB: 2010 - Grade: 7


In [ ]:
# 2(e)
print(f"\nAverage year of birth (teachers): {ward1.compute_average()}")


Average year of birth (teachers): 1982.0


TRẮC NGHIỆM

In [ ]:
# cau 5
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name: str, yob: int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Student(Person):
    def __init__(self, name: str, yob: int, grade: str):
        super().__init__(name, yob)
        self._grade = grade

    def describe(self):
        print(f"Student - Name: {self._name} - YoB: {self._yob} - Grade: {self._grade}")

# Create an instance of Student
student1 = Student(name="studentZ2023", yob=2011, grade="6")
assert student1._yob == 2011
student1.describe()

Student - Name: studentZ2023 - YoB: 2011 - Grade: 6


In [ ]:
# cau 6
class Person(ABC):
    def __init__(self, name: str, yob: int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Teacher(Person):
    def __init__(self, name: str, yob: int, subject: str):
        super().__init__(name, yob)
        self._subject = subject

    def describe(self):
        print(f"Teacher - Name: {self._name} - YoB: {self._yob} - Subject: {self._subject}")

# Create an instance of Teacher
teacher1 = Teacher(name="teacherZ2023", yob=1991, subject="History")
assert teacher1._yob == 1991
teacher1.describe()

Teacher - Name: teacherZ2023 - YoB: 1991 - Subject: History


In [ ]:
# cau 7
class Person(ABC):
    def __init__(self, name: str, yob: int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Doctor(Person):
    def __init__(self, name: str, yob: int, specialist: str):
        super().__init__(name, yob)
        self._specialist = specialist

    def describe(self):
        print(f"Doctor - Name: {self._name} - YoB: {self._yob} - Specialist: {self._specialist}")

# Create an instance of Doctor
doctor1 = Doctor(name="doctorZ2023", yob=1981, specialist="Endocrinologists")
assert doctor1._yob == 1981
doctor1.describe()

Doctor - Name: doctorZ2023 - YoB: 1981 - Specialist: Endocrinologists


In [ ]:
# cau 8
class Ward:
    def __init__(self, name: str):
        self.__name = name
        self.__listPeople = []

    def add_person(self, person: Person):
        self.__listPeople.append(person)

    def describe(self):
        print(f"Ward Name: {self.__name}")
        for p in self.__listPeople:
            p.describe()

    def count_doctor(self):
        count = 0
        for person in self.__listPeople:
            if isinstance(person, Doctor):
                count += 1
        return count

# Assuming the classes Person, Student, Teacher, and Doctor are defined as per previous examples
student1 = Student(name="studentA", yob=2010, grade="7")
teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
teacher2 = Teacher(name="teacherB", yob=1995, subject="History")
doctor1 = Doctor(name="doctorA", yob=1945, specialist="Endocrinologists")
doctor2 = Doctor(name="doctorB", yob=1975, specialist="Cardiologists")

ward1 = Ward(name="Ward1")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)

# Count the number of doctors
print(ward1.count_doctor())

2


CÂU 3

In [ ]:
class MyStack:
    def __init__(self, capacity):
        self.capacity = capacity
        self.stack = []

    def is_empty(self):
        return len(self.stack) == 0

    def is_full(self):
        return len(self.stack) == self.capacity

    def push(self, value):
        if not self.is_full():
            self.stack.append(value)
        else:
            raise Exception("Stack is full")

    def pop(self):
        if not self.is_empty():
            return self.stack.pop()
        else:
            raise Exception("Stack is empty")

    def top(self):
        if not self.is_empty():
            return self.stack[-1]
        else:
            raise Exception("Stack is empty")


In [ ]:
stack1 = MyStack(capacity=5)

stack1.push(1)
stack1.push(2)

print(stack1.is_full())
print(stack1.top())
print(stack1.pop())
print(stack1.top())
print(stack1.pop())
print(stack1.is_empty())

False
2
2
1
1
True


TRẮC NGHIỆM

In [ ]:
# cau 9
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_full(self):
        return len(self.__stack) == self.__capacity

    def push(self, value):
        if not self.is_full():
            self.__stack.append(value)
        else:
            raise Exception("Stack is full")

stack1 = MyStack(capacity=5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print(stack1.is_full())

False


In [ ]:
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_full(self):
        return len(self.__stack) == self.__capacity

    def push(self, value):
        if not self.is_full():
            self.__stack.append(value)
        else:
            raise Exception("Stack is full")

    def top(self):
        if not self.is_empty():
            return self.__stack[-1]
        else:
            raise Exception("Stack is empty")

    def is_empty(self):
        return len(self.__stack) == 0

stack1 = MyStack(capacity=5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print(stack1.top())

2


CÂU 4

In [ ]:
class MyQueue:
    def __init__(self, capacity):
        self.capacity = capacity
        self.queue = []

    def is_empty(self):
        return len(self.queue) == 0

    def is_full(self):
        return len(self.queue) == self.capacity

    def enqueue(self, value):
        if not self.is_full():
            self.queue.append(value)
        else:
            raise Exception("Queue is full")

    def dequeue(self):
        if not self.is_empty():
            return self.queue.pop(0)
        else:
            raise Exception("Queue is empty")

    def front(self):
        if not self.is_empty():
            return self.queue[0]
        else:
            raise Exception("Queue is empty")

In [ ]:
queue1 = MyQueue(capacity=5)

queue1.enqueue(1)
queue1.enqueue(2)

print(queue1.is_full())
print(queue1.front())
print(queue1.dequeue())
print(queue1.front())
print(queue1.dequeue())
print(queue1.is_empty())

False
1
1
2
2
True


In [ ]:
# cau 11
queue1 = MyQueue(capacity=5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print(queue1.is_full())

False


In [ ]:
# cau 12
queue1 = MyQueue(capacity=5)
queue1.enqueue(1)
assert queue1.is_full() == False
print(queue1.front())

1
